language: node_js
sudo: false
node_js:
- 6
- 5
- 4
- '0.12'
- iojs
matrix:
  include:
  - node_js: 6
    env: DEPLOY=true
after_success: if [[ $DEPLOY == "true" ]] ; then ./node_modules/.bin/gulp condensation:deploy
  ; else echo "no deploy" ; fi
deploy:
  provider: npm
  email: as.us.labs@sungardas.com
  api_key:
    secure: bliR6XWYQX5/QnHMNCNU/QBdGxjySDSzr9D0Hk7itOAdO+1krg8TOIAzuNTT4HulfbYGRBUvDe5c4Oyx5PEYV0mWQRxyXJfA1AT/tUWvpiwcwowXaFltPNIiQkBzff+YGB3d8TJJGLtQuAKqKq6nidMOr5VdHGr4PnxrWOQ5aSMezY1iySBimMRCglnyBEYmIsAYZcKB9JJS/ahuitKWvR6cYq0dRgYJlx/gdZy0fJM2Jv8x+4ZeJ6amBNx1uNwqwiwIRx6lw+g9b0sIyjpol7w2TruULnokOsr+tSbpfoh8FIS5NOmJbvwjlUNRRxRCbXHjsBVOJvs2epAnFZm3cL5b5XuTXpebYW1CeuoMdcfS/Uqv3jVsB32AyFUKAKHv6EklnyLWHQjOftoNbudXrS0BSo84LMioj3m0VXE+QeTXdWUrkc1glEX79y0r/ZzOsxNx2wI+g1hVLANDCLRvlFTRP8j9Cw8n62XRXt+U9KHnEDfm7O4ndOpaoztCUHiWhL0tJ+U5dlVoTYtVuDnpXODtie4TAah4HM3hwylZ8ZD16/X/QW+600eYl1vWj2OqsP9mcdezjyyNte6f38Q3gVaiL2Pb173ekmEhjeyjHmnFRxuyBhBXKYLPf8sGYdRcgBE/hVFQKYzPi17/dkycaCVE3KKfmR/6SGXzlg8lpR4=
  on:
    tags: true
    repo: SungardAS/particles-lambda
    node: 6
env:
  global:
  - secure: bk0snObUcjOc5CLELWiZXivHy02XVB0MrvoWU5tWsefKd52UaXkprpIyOougVjtjI6Vr+lRVlQwNqLQjvSGRiKJqSay/isAWhkHo3Yyglrn/XBWJm/ejcG96BwJlYUtzkmMMwSXc0k7Wjx9jUYbKZ9sNa9azXVRlI7K3M8W2LSDPeudW80G3pcM/R9K13Lbb/3Lc7abla2hn7BycquSaxBvkXSKZkfS8RVu9mR3r5xIvQJF3DQwGZqbpq6D5z6pecFjEM4V8/u51YlCiLeUnrfh0+bJnsI3QyaVdxcgJ5ga7CNQzMOXbIylzEG/LO9mnFxu4z0QvIdD1zYFEHtyRVoyYNuBig9pYr1UeNdKu8cm/tI1U3MqQz6Zy3HmbLeOq/xe2Qsz1ME98XRF2YGrsV9+9zje5X3zcXi0Je/oiOUd4q42FI1F93aN9liZ5HfL1TG22cmluuIGu5VBq/tZmy1FjX/H4WmQ87+R7dn1x9xyFBURTi2khn+WdVkMw+d49SfwbgZ6nD87hFMWgNUb2i0Ee1j4c+wUFOI+PnY63DjBvJS6zhk8sXGjYz7nVLRZCSad+buZTS8Awr36P3N27Kd3o6A54aXF6UNGr699NpwpbLSQ9B1ZPzBc2GRoEqaTZ+UVtcHgn7aRkIwrbjLAOQRQdcVW8BlgTiXl0q+4vvqE=
  - secure: FGbkckLmaotY3XwET5zP2A5gNaFGMytsePUWeLqgRrGzc6K/8yxffE8kSsLWchVAgKGR0PLClwEx826ls964/j9MfDCSHH9qtygvobH38oqFuc1ANBcVxzvhdfTOsF8ueFkOaF1LqnSvhUxsKMCZdcc0bJKcfhG7a6aKYcrXAnutncU8Vz/wMQe6nsYfPEf1Tef16VjLxhHkIWhZaXFsgdNAH+ilpIuReF/G3Tk0obHANi1yA1alVsAjftqOWExVtGgOqHXWctQNoWUS4MfC86t4VDSPpHVRDzCh14BjPCaMDsvd+dmSLO++CUA3Wtputys7rxD9xecdTGvHyb0104Tqya+WyFTtrju2dEAjTkVtAMDMwSB1DsquYtz+ISYV1o+OylNzw1M3MqMDyYn9PJJIoW//pUl22POEJKURagcCIoxjCHXUP1+xgTdcPdl1qEI4chTGRes3NYE7Pgn31f27X+aQrf2Am5aApLeXSR87A9ZGc3RmXeZes0Uj0YNzrbrBK62Cp8Ft3aWfavtKUioI5fW/Hz3uvWU23+VBNtlTMTdk9Gr85lJLiAQElC79HP2Im0A85Xr1f9jqnnHH+m7q2Cu6+VfIXShj51vgCFwA3VABzX9YiVWMoaLo8EP4UzH33gI7kVngZ8l7xTin12cgIGhKP+0DHDwGnE3BIe8=
